// Generated by scripts/import-transportation-book.ts. Do not edit.
import file0 from './transportation/INDEX.md' with { type: 'text' }
import file1 from './transportation/ATTRIBUTION.md' with { type: 'text' }
import manifest from './transportation/references/manifest.json'
import file3 from './transportation/references/00-book-overview.md' with {
  type: 'text',
}
import file4 from './transportation/references/00-front-matter--01-titlepage.md' with {
  type: 'text',
}
import file5 from './transportation/references/00-front-matter--02-infopage.md' with {
  type: 'text',
}
import file6 from './transportation/references/00-front-matter--about-the-authors.md' with {
  type: 'text',
}
import file7 from './transportation/references/00-front-matter.md' with {
  type: 'text',
}
import file8 from './transportation/references/01-introduction-and-planning--1-01-fundamentals-of-transportation-introduction.md' with {
  type: 'text',
}
import file9 from './transportation/references/01-introduction-and-planning--1-02-fundamentals-of-transportation-and-decision-making.md' with {
  type: 'text',
}
import file10 from './transportation/references/01-introduction-and-planning--1-03-evaluation.md' with {
  type: 'text',
}
import file11 from './transportation/references/01-introduction-and-planning.md' with {
  type: 'text',
}
import file12 from './transportation/references/02-planning-models--2-01-modeling.md' with {
  type: 'text',
}
import file13 from './transportation/references/02-planning-models--2-02-data.md' with {
  type: 'text',
}
import file14 from './transportation/references/02-planning-models--2-03-networks.md' with {
  type: 'text',
}
import file15 from './transportation/references/02-planning-models--2-04-modes.md' with {
  type: 'text',
}
import file16 from './transportation/references/02-planning-models.md' with {
  type: 'text',
}
import file17 from './transportation/references/03-modeling-methods--3-01-agent-based-modeling.md' with {
  type: 'text',
}
import file18 from './transportation/references/03-modeling-methods--3-02-choice-modeling.md' with {
  type: 'text',
}
import file19 from './transportation/references/03-modeling-methods--3-03-land-use-forecasting.md' with {
  type: 'text',
}
import file20 from './transportation/references/03-modeling-methods--3-04-trip-generation.md' with {
  type: 'text',
}
import file21 from './transportation/references/03-modeling-methods--3-05-destination-choice.md' with {
  type: 'text',
}
import file22 from './transportation/references/03-modeling-methods--3-06-3-6-route-choice.md' with {
  type: 'text',
}
import file23 from './transportation/references/03-modeling-methods.md' with {
  type: 'text',
}
import file24 from './transportation/references/04-transit--4-01-transit-demand.md' with {
  type: 'text',
}
import file25 from './transportation/references/04-transit--4-02-transit-operations-and-capacity.md' with {
  type: 'text',
}
import file26 from './transportation/references/04-transit--4-03-network-design-and-frequency.md' with {
  type: 'text',
}
import file27 from './transportation/references/04-transit--4-04-timetabling-and-scheduling.md' with {
  type: 'text',
}
import file28 from './transportation/references/04-transit--4-05-traveler-information-for-transit.md' with {
  type: 'text',
}
import file29 from './transportation/references/04-transit.md' with {
  type: 'text',
}
import file30 from './transportation/references/05-traffic--5-01-queueing.md' with {
  type: 'text',
}
import file31 from './transportation/references/05-traffic--5-02-traffic-flow.md' with {
  type: 'text',
}
import file32 from './transportation/references/05-traffic--5-03-queueing-and-traffic-flow.md' with {
  type: 'text',
}
import file33 from './transportation/references/05-traffic.md' with {
  type: 'text',
}
import file34 from './transportation/references/06-traffice-control--6-01-shockwaves.md' with {
  type: 'text',
}
import file35 from './transportation/references/06-traffice-control--6-02-traffic-signals.md' with {
  type: 'text',
}
import file36 from './transportation/references/06-traffice-control--6-03-traffic-control-devices.md' with {
  type: 'text',
}
import file37 from './transportation/references/06-traffice-control--6-04-metering-and-analogs.md' with {
  type: 'text',
}
import file38 from './transportation/references/06-traffice-control.md' with {
  type: 'text',
}
import file39 from './transportation/references/07-geometric-design--7-01-sight-distance.md' with {
  type: 'text',
}
import file40 from './transportation/references/07-geometric-design--7-02-grade.md' with {
  type: 'text',
}
import file41 from './transportation/references/07-geometric-design--7-03-earthwork.md' with {
  type: 'text',
}
import file42 from './transportation/references/07-geometric-design--7-04-horizontal-curves.md' with {
  type: 'text',
}
import file43 from './transportation/references/07-geometric-design--7-05-vertical-curves.md' with {
  type: 'text',
}
import file44 from './transportation/references/07-geometric-design.md' with {
  type: 'text',
}
import file45 from './transportation/references/zz-back-matter--20-glossary.md' with {
  type: 'text',
}
import file46 from './transportation/references/zz-back-matter.md' with {
  type: 'text',
}

export const TRANSPORTATION_FILES: Record<string, string> = {
  'INDEX.md': file0,
  'ATTRIBUTION.md': file1,
  'references/manifest.json': JSON.stringify(manifest, null, 2) + '\n',
  'references/00-book-overview.md': file3,
  'references/00-front-matter--01-titlepage.md': file4,
  'references/00-front-matter--02-infopage.md': file5,
  'references/00-front-matter--about-the-authors.md': file6,
  'references/00-front-matter.md': file7,
  'references/01-introduction-and-planning--1-01-fundamentals-of-transportation-introduction.md':
    file8,
  'references/01-introduction-and-planning--1-02-fundamentals-of-transportation-and-decision-making.md':
    file9,
  'references/01-introduction-and-planning--1-03-evaluation.md': file10,
  'references/01-introduction-and-planning.md': file11,
  'references/02-planning-models--2-01-modeling.md': file12,
  'references/02-planning-models--2-02-data.md': file13,
  'references/02-planning-models--2-03-networks.md': file14,
  'references/02-planning-models--2-04-modes.md': file15,
  'references/02-planning-models.md': file16,
  'references/03-modeling-methods--3-01-agent-based-modeling.md': file17,
  'references/03-modeling-methods--3-02-choice-modeling.md': file18,
  'references/03-modeling-methods--3-03-land-use-forecasting.md': file19,
  'references/03-modeling-methods--3-04-trip-generation.md': file20,
  'references/03-modeling-methods--3-05-destination-choice.md': file21,
  'references/03-modeling-methods--3-06-3-6-route-choice.md': file22,
  'references/03-modeling-methods.md': file23,
  'references/04-transit--4-01-transit-demand.md': file24,
  'references/04-transit--4-02-transit-operations-and-capacity.md': file25,
  'references/04-transit--4-03-network-design-and-frequency.md': file26,
  'references/04-transit--4-04-timetabling-and-scheduling.md': file27,
  'references/04-transit--4-05-traveler-information-for-transit.md': file28,
  'references/04-transit.md': file29,
  'references/05-traffic--5-01-queueing.md': file30,
  'references/05-traffic--5-02-traffic-flow.md': file31,
  'references/05-traffic--5-03-queueing-and-traffic-flow.md': file32,
  'references/05-traffic.md': file33,
  'references/06-traffice-control--6-01-shockwaves.md': file34,
  'references/06-traffice-control--6-02-traffic-signals.md': file35,
  'references/06-traffice-control--6-03-traffic-control-devices.md': file36,
  'references/06-traffice-control--6-04-metering-and-analogs.md': file37,
  'references/06-traffice-control.md': file38,
  'references/07-geometric-design--7-01-sight-distance.md': file39,
  'references/07-geometric-design--7-02-grade.md': file40,
  'references/07-geometric-design--7-03-earthwork.md': file41,
  'references/07-geometric-design--7-04-horizontal-curves.md': file42,
  'references/07-geometric-design--7-05-vertical-curves.md': file43,
  'references/07-geometric-design.md': file44,
  'references/zz-back-matter--20-glossary.md': file45,
  'references/zz-back-matter.md': file46,
}
